source "https://rubygems.org"
ruby '2.5.1'
gem 'bundler'
gem 'twitter'
gem 'gmail'
gem 'gmail_xoauth'
gem 'nokogiri'
gem 'json'
gem 'googleauth'
gem 'fileutils'
gem 'rubocop', '~> 0.57.2'
gem 'dotenv'
